---
##
# Refer to JBoss Data Grid documentation
# https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.4/html/Installation_Guide/sect-Service_Configuration.html#Install_JBoss_Enterprise_Application_Platform_6_Red_Hat_Enterprise_Linux_Service
# https://access.redhat.com/documentation/en/red-hat-jboss-enterprise-application-platform/7.0.beta/installation-guide/chapter-4-configuring-jboss-Data Grid-to-run-as-a-service
##


- name: Create JBoss Data Grid Group
  group:
    name: "{{ jboss_datagrid_group }}"
    system: yes
    state: present
    gid: "400"
  tags:
    - jboss_datagrid

- name: Create JBoss Data Grid User
  user:
    name: "{{ jboss_datagrid_user }}"
    comment: "JBoss Data Grid User"
    uid: "400"
    group: "{{ jboss_datagrid_group }}"
    home: "{{ jboss_datagrid_library_dest }}"
    shell: "/bin/bash"
  tags:
    - jboss_datagrid

- name: Create JBoss Data Grid Library Destination
  become: true
  file:
    path: "{{ jboss_datagrid_library_dest }}"
    owner: "{{ jboss_datagrid_user }}"
    group: "{{ jboss_datagrid_group }}"
    state: directory
    mode: "755"
  tags:
    - jboss_datagrid

- name: Create JBoss Data Grid Service Conf Directory
  file:
    path: "{{ jboss_datagrid_service_conf_dir }}"
    owner: "{{ jboss_datagrid_user }}"
    group: "{{ jboss_datagrid_group }}"
    state: directory
    mode: "755"
  tags:
    - jboss_datagrid

## TODO this copy needs to happen iteratively for each node configured using jboss_datagrid_nodes
- name: Copy JBoss Data Grid Service Conf File
  template:
    owner: "{{ jboss_datagrid_user }}"
    group: "{{ jboss_datagrid_group }}"
    src: jboss-as.conf.j2
    dest: "{{ jboss_datagrid_service_conf_file | regex_replace('.conf$','-node-'+item+'.conf')}}"
    backup: yes
    mode: "755"
  vars: 
    node_name: "node-{{item}}"
    node_id: "node{{item}}.{{ansible_ssh_host}}"
    jboss_datagrid_run_extra_args: " -Djboss.server.base.dir={{jboss_datagrid_library_dest}}/node-{{item}} -Djboss.socket.binding.port-offset={{ ( item | int) * (100|int) }}"
  with_sequence: count="{{jboss_datagrid_nodes}}"
  tags:
    - jboss_datagrid

- name: Create JBoss Data Grid Service Log Directory
  file:
    path: "{{ jboss_datagrid_service_log_dir }}"
    owner: "{{ jboss_datagrid_user }}"
    group: "{{ jboss_datagrid_group }}"
    state: directory
    mode: "755"
  tags:
    - jboss_datagrid

- name: Create JBoss Data Grid Service Runtime Data Directory
  file:
    path: "{{ jboss_datagrid_service_data_dir }}"
    owner: "{{ jboss_datagrid_user }}"
    group: "{{ jboss_datagrid_group }}"
    state: directory
    mode: "755"
  tags:
    - jboss_datagrid
