
## TODO check in EL 6 
- name: Restart Jboss Datagrid Services
  become: true
  service:
    name: "{{ jboss_datagrid_service_name }}-node-{{item}}"
    state: restarted
  with_sequence: count="{{jboss_datagrid_nodes}}"
  tags:
    - jboss_eap

# Sanity test if everything was setup right and JBoss is running
- name: Verify jboss datagrid nodes is running
  wait_for: port="{{(11222|int)+( item | int) * (100|int)}}" host="{{ jboss_datagrid_bind_web_address }}" timeout=120
  notify: Check jboss datagrid nodes is available
  with_sequence: count="{{jboss_datagrid_nodes}}"

- name: Check jboss datagrid nodes is available
  uri:
    url: "http://{{jboss_datagrid_bind_web_address}}:{{(11222|int)+( item | int) * (100|int)}}"
  with_sequence: count="{{jboss_datagrid_nodes}}"